---
#Install Mariadb Server Packages
- name: 1. Mariadb Repository
  template:
    src: templates/mariadb.repo.j2
    dest: /etc/yum.repos.d/mariadb.repo

- name: 2. Install Mariadb Server packages
  yum:
    name:
    - MariaDB-server
    - MariaDB-client
    - MySQL-python
    state: installed
  tags:
    - InstallMariadb

#Starting mariadb Services
- name: 3. Starting Mariadb Services
  service:
    name: mariadb
    enabled: yes
    state: started

#Check If root password is set
- name: 4. Check root password is set
  shell: >
    mysqladmin -u root status
  changed_when: false
  failed_when: false
  register: root_pwd_check
  tags: mariadb

#Set root mariadb password
- name: 5. Set MariaDB root password for the firsttime
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: localhost
    state: present
  when: root_pwd_check.rc == 0
  tags: mariadb

- name: 6. Set mariadb root password for localhost (127.0.0.1)
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: "{{ item }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present
  with_items:
    - ::1
    - 127.0.0.1
  when: root_pwd_check.rc == 0
  tags: mariadb
